### PR TITLE
Support PostgreSQL + Deploy to Heroku

### PR DESCRIPTION
**Pull request by jacobwegner**
This PR:

- Add some scaffolding to deploy to Heroku
  - [Subdir buildpack](https://elements.heroku.com/buildpacks/sectorlabs/heroku-buildpack-subdir) to deploy app from `server/`
  - [Python poetry buildpack](https://elements.heroku.com/buildpacks/moneymeets/python-poetry-buildpack) to use Poetry to generate requirements.txt files
  - https://devcenter.heroku.com/articles/django-app-configuration
  - https://devcenter.heroku.com/articles/django-assets
- Adds support / docs for using PostgreSQL as the database
- Optimizes the `0004_auto_20230306_1456.py` migration by making use of [bulk_create](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#bulk-create)
- Adds [tqdm](https://github.com/tqdm/tqdm) for a pretty progress bar

We should revisit an ingestion pipeline in the future, but optimizing the migration helps if we need to blow away a local database `dropdb alignmentapi` and start over.

### CODE REVIEW

**Comment by jacobwegner** [comment]
@themikejr Let's see how far we get with this.  I can easily help deploy the frontend to the same Heroku app if you need that too.

If we were to deploy the frontend elsewhere or if you wanted to point a local frontend at Heroku we'd probably want to add [django-cors-headers](https://pypi.org/project/django-cors-headers/).

**Comment by themikejr** [comment]
@jacobwegner thanks for all of this, it's really helpful! 

For some reason I had to change the location of the data path in that migration to be like:

```python
DATA_PATH = settings.BASE_DIR / "data/data"
```

I'm guessing this is because I didn't document where the data is supposed to go and we ended up with two different locations?

**Comment by themikejr** [comment]
After tinkering with my local postrgres creds, I was able to run this branch locally using postrgres and everything seems to be working properly.

**Review by themikejr — APPROVED** [review]

**Comment by jacobwegner** [comment]
You're welcome!

**Pull request merged**
